### ISSUE TITLE
SSH auth. Can't start new feature. Git flow. 

### ISSUE THREAD

**Issue by GreenKn1ght** [sboulema/TGit#11]
At pull stage it said that can't read from remote repo, but i can do it from tortoisegit client. SSH auth. Also successfully started new feature from SourceTree.

**Comment by sboulema** [comment]
Are you able to pull from the command line?

**Comment by GreenKn1ght** [comment]
Erm. Same message from git bash.

```
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

But i cloned it with loading ppk. And putty auth agent working now =/

**Comment by sboulema** [comment]
TGIT doesn't do anything with credentials and just assumes the repo is correctly setup. If you can pull from git bash the gitflow feature will also work :)

**Comment by GreenKn1ght** [comment]
Could you enhance it? I can pull from TortoiseGit, SourceTree and another not really famous client. Also last client showed me it:
![default](https://cloud.githubusercontent.com/assets/19373816/17431284/ec575f18-5b01-11e6-9290-4b36db7fb922.PNG)
I have no idea why i can't pull from Git Bash, but if i can from clients...

**Comment by sboulema** [comment]
Will look into it :)

**Comment by sboulema** [comment]
Can you please try this new version?

[TGIT_3.4.1.zip](https://github.com/sboulema/TGIT/files/403700/TGIT_3.4.1.zip)

What it does:
- read the keyfile location from the remote.origin.puttykeyfile config
- start pageant with the keyfile
- get the path to TortoiseGitPlink from the registry
- for all flow operations in TGIT (temporarily) set GIT_SSH to the TortoiseGitPlink path

Uses stuff already part of the TortoiseGit install and TGIT doesn't have to do anything with credentials

**Comment by GreenKn1ght** [comment]
3.4.1 succefully created new feature branch. Work as expected:)

**Comment by sboulema** [comment]
Great to hear! Thanks for testing :)
