### ISSUE TITLE
High DPI icons

### ISSUE THREAD

**Issue by ygoe** [sboulema/TGit#12]
Visual Studio now has high resolution icons, TGIT might also do that.

**Comment by sboulema** [comment]
Info about High DPI icons: [Image Service and Catalog](https://msdn.microsoft.com/en-US/library/mt628927.aspx?f=255&MSPPError=-2147217396)
Examples: [VSSDK-Extensibility-Samples](https://github.com/Microsoft/VSSDK-Extensibility-Samples)
Icons: [Octoicons](https://octicons.github.com/), [Octoicons svg->png](http://fa2png.io/r/octicons/), [svg->xaml](https://github.com/BerndK/SvgToXaml)
