### ISSUE TITLE
Git is named "Git"

### ISSUE THREAD

**Issue by ygoe** [sboulema/TGit#13]
Not "GIT" and not "git". This is used inconsistently in the project website, UI and other places. It looks strange. I guess the "correct" abbreviation of TortoiseGit would be TGit, and so should be the menu in Visual Studio, as well as the name of this extension. (And this GitHub repository…)

**Comment by sboulema** [comment]
Good observation! The small details also matter :) Rename will be in the next release.

**Comment by ygoe** [comment]
@sboulema Shouldn't this also be changed in [TGIT.vsct](https://github.com/sboulema/TGit/blob/master/TGit/TGIT.vsct#L14) (4 occurrences)? I see the main menu entry "TGIT" while Visual Studio 2017 is loading. When loading is done, the label changes to "TGit" which probably comes from the then running extension code.

**Comment by sboulema** [comment]
Renamed in the next release!

**Comment by ygoe** [comment]
Thank you!
