### ISSUE TITLE
TGit shows me only GitHubFlow. 

### ISSUE THREAD

**Issue by GreenKn1ght** [sboulema/TGit#17]
3.5 version. GitFlow initiated from SourceTree, and i can start feature, finish feature etc. 
SourceTree (yeah, russian words, but you can belive me, it says GitFlow is OK):
![default](https://cloud.githubusercontent.com/assets/19373816/17559925/b611163a-5f28-11e6-961c-99b629aae968.png)

But TGit showed me:
![default](https://cloud.githubusercontent.com/assets/19373816/17560048/3daeb50c-5f29-11e6-83e3-2132a1fbe5ee.png)

That "not realy famous" app show me it:
![default](https://cloud.githubusercontent.com/assets/19373816/17559764/0774a4c0-5f28-11e6-8f1a-6456831d8cf6.PNG)

**Comment by sboulema** [comment]
TGit looks at Tools -> Options -> TGit -> Flow master and development branch option. If the master and development branch exist remotely it will show GitFlow, if there is a master branch and no development branch it will show GitHubFlow.

Will fix and look at the gitflow settings of the repo.

Is this a SSH or HTTP repo?

**Comment by sboulema** [comment]
Could you please try this version: [TGit_3.5.1.zip](https://github.com/sboulema/TGit/files/412830/TGit_3.5.1.zip)

It uses the git config to determine which flow is used and it has a GitFlow Init option to set the configs

**Comment by GreenKn1ght** [comment]
Got it, my develop branch named "devel", I must rename it or just change name in TGit config.
SSH repo.

About 3.5.1:
After instal it showed GitHubFlow and GitFlow.
GitFlow -> Init created (ignoring some warning (below)) new branch "develop" from master and yes, now i can use GitFlow. But i suppose TGit should just use git config, not create new branch. 

`warning: unable to rmdir *here submodule path .git*: Directory not empty`

**Comment by GreenKn1ght** [comment]
After Init i tried change TGit config -> Flow -> develop branch name, and changes are not applied. Then i restart VS and after loading TGit extenstion was disabled O_o. And i think now i have TGit 3.5, because in config develop branch name is "develop" and TGit show me only GitHubFlow (like before 3.5.1).

**Comment by sboulema** [comment]
Could you please try this version: [TGit_3.5.2.zip](https://github.com/sboulema/TGit/files/414996/TGit_3.5.2.zip)

This version does away with the TGit flow options and only uses the git config.

**Comment by GreenKn1ght** [comment]
For repo with Git flow detected succefully.
