### ISSUE TITLE
Trying to finish feature

### ISSUE THREAD

**Issue by GreenKn1ght** [sboulema/TGit#18]
```
> git checkout devel 
M   (**submodule** path)
Your branch is up-to-date with 'origin/devel'.
Switched to branch 'devel'
> git pull 
Already up-to-date.
> git merge --no-ff feature/MS-712 **(it must be WMS-712)**
merge: feature/MS-712 **(Again)** - not something we can merge

Error (2919 ms @ 15.08.2016 11:59:33)
```

So, in my case submodule changed without creating new branch and now with head on devel.
Expected simple behaviour: TGit just merge main repo without submodules.
Expected extended behaviour: TGit gives me a choose a submodules to merge or only if my submodule head on feature/.., shows me error (or choice) ("Your submodule stand on feature branch, pls merge it").

**Comment by sboulema** [comment]
It looks like it is not handling spaces in branch names correctly

**Comment by sboulema** [comment]
How did you create the branch? 

Please try this: switch to the branch and then execute 'git symbolic-ref -q --short HEAD', what is the output?

**Comment by GreenKn1ght** [comment]
```
$ git symbolic-ref -q --short HEAD
feature/WMS-712
```

It's correct name. 
I do not remember exactly how I created the branch, but it was either TGit or SourceTree with GitFlow.

**Comment by sboulema** [comment]
Found it, will be fixed in the next version

**Comment by GreenKn1ght** [comment]
Thank you!
