### ISSUE TITLE
VisualStudio will freeze at frequently.

### ISSUE THREAD

**Issue by ryo1988** [sboulema/TGit#22]
VisualStudio will freeze at frequently.
v3.6
VS2015
git for windows 2.9.3
TortoiseGit 2.2.0.0

**Comment by GreenKn1ght** [comment]
Have you tried disable TGit?

**Comment by ryo1988** [comment]
Yes. I tried.

**Comment by ryo1988** [comment]
Non freeze, After disabling TGIT.

**Comment by sboulema** [comment]
Can you please describe what you mean with freezes. While using TGit functions, during startup, during saving, etc...

**Comment by ryo1988** [comment]
TGIT only have enabled, even if they are not used at all, overall very performance is deteriorated, and then freeze, such as during code editing.

**Comment by sboulema** [comment]
Looking into it, can confirm that something is not performing well.

**Comment by ryo1988** [comment]
In v3.5 there was no problem.

**Comment by sboulema** [comment]
Should be better with the 3.7 release!

**Comment by ryo1988** [comment]
thanks!
