### ISSUE TITLE
Add an indication that the repository is dirty.

### ISSUE THREAD

**Issue by GreenKn1ght** [sboulema/TGit#24]
Something like this
![default](https://cloud.githubusercontent.com/assets/19373816/17739408/a803455c-649d-11e6-8918-46fa43a074b9.PNG)

It would be nice. If it possible, of course (something tells me that it's impossible).

**Comment by sboulema** [comment]
Was thinking about this myself also. Am I correct in assuming that the number would the number of commits your local branch is behind the remote branch?

Will look into after I have fixed #22

**Comment by GreenKn1ght** [comment]
I'm thinking about number of uncommitted files, but your idea nice too.

**Comment by GreenKn1ght** [comment]
Only now I noticed that git extenstion for VS shows both numbers.
![234](https://cloud.githubusercontent.com/assets/19373816/17775180/bacf6bc6-655f-11e6-8520-0d52d4631b69.PNG)

**Comment by sboulema** [comment]
Oh duh completely forgot about that. In that case I wouldn't want to recreate that functionality I guess
