### ISSUE TITLE
Clicking on [TGit] menu of the main menu takes about 4 seconds to open the menu

### ISSUE THREAD

**Issue by pertheli** [sboulema/TGit#26]
Is there any way to make the menu open faster?
Opening the context menu doesn't take time though.

VS 2015 Update 2
TGit V 3.7, 3.6

**Comment by sboulema** [comment]
It is doing a lot of checks, which menu items should be visible/enabled. Trying to speed it up for a while now, but it is proving quite difficult. Will look into it some more!

**Comment by sboulema** [comment]
Can you please try if this version is faster? 
[TGit_3.7.1.zip](https://github.com/sboulema/TGit/files/429961/TGit_3.7.1.zip)

**Comment by pertheli** [comment]
Thanks, the new version seems faster, but still there is about about 2 maybe 3 seconds lag.

Strangely, once the menu is opened, and if i do not execute/select any menu item, then the menu opens instantly. But after executing any menu item(of TGit or of other menu) then reopening the TGit menu is taking time.

**Comment by sboulema** [comment]
Can you please try this version: [TGit_3.7.3.zip](https://github.com/sboulema/TGit/files/432820/TGit_3.7.3.zip)

**Comment by pertheli** [comment]
Thanks. The menu opens instantly now!
