### ISSUE TITLE
After GitFlow -> Init in "GitFlow" available only "Init" until restart VS.

### ISSUE THREAD

**Issue by GreenKn1ght** [sboulema/TGit#27]
I tried Init several times and each time was required to restart Visual Studio to gain access to the functions of GitFlow.

**Comment by sboulema** [comment]
Please try this version: 
[TGit_3.7.4.zip](https://github.com/sboulema/TGit/files/436493/TGit_3.7.4.zip)

**Comment by GreenKn1ght** [comment]
Tried 3.8, bug still exists.
3.7.4 includes changes that are not in 3.8?

**Comment by sboulema** [comment]
Weird 3.8 has the 3.7.4 changes included. Will look into it some more

**Comment by sboulema** [comment]
Please try this version [TGit_3.8.1.zip](https://github.com/sboulema/TGit/files/439579/TGit_3.8.1.zip)

**Comment by GreenKn1ght** [comment]
3.8.1 works fine.

**Comment by sboulema** [comment]
Awesome :D
