### ISSUE TITLE
Please add "Browse References" menu

### ISSUE THREAD

**Issue by pertheli** [sboulema/TGit#28]
It would be nice if you could add the "Browse References" menu.
Also if possible, "Submodule Update..."

**Comment by sboulema** [comment]
"Browse References" will be added in the next version!

"Submodule Update" can be done through the "Sync" option, Is that good enough? I understand it is a mouse click more but the main menu is getting really crowded :p

**Comment by sboulema** [comment]
"Browse References" is available in 3.8

Keep an eye out for #23 for the submodule features
