### ISSUE TITLE
Add option "push after finish feature" 

### ISSUE THREAD

**Issue by GreenKn1ght** [sboulema/TGit#29]
Auto merge sometimes can to surprise, you know (someone deleted resources wich u used in your feature branch, for Git it's ok, but not for compiler :)).
After merge and before pushing to remote i prefer rebuild solution, start tests and may be check in runtime by myself.

**Comment by sboulema** [comment]
Option added in upcoming 3.9 release, you can test it with this 3.8.1 build: 
[TGit_3.8.1.zip](https://github.com/sboulema/TGit/files/439579/TGit_3.8.1.zip)
