### ISSUE TITLE
Features in TGit -> TGit doesn't work when is no active document`s tab. 

### ISSUE THREAD

**Issue by GreenKn1ght** [sboulema/TGit#34]
When i try to use features from TGit -> TGit occurs an error "Object reference not set to an instance of an object". It's not happen if there is active document`s tab.

![1](https://user-images.githubusercontent.com/19373816/27646173-a058792c-5c30-11e7-8789-9f337b8f3b40.png)
![2](https://user-images.githubusercontent.com/19373816/27646172-a0576672-5c30-11e7-97c9-29a88863f9b1.png)

**Comment by sboulema** [comment]
All those menu items are file specific operations and can not work without an active document. The new release 4.7 now correctly disables those items when no file is opened
