### ISSUE TITLE
can not use in vs2013

### ISSUE THREAD

**Issue by jin925** [sboulema/TGit#37]
在我配置tgit的时候发生了错误，并功能不可用，我已经按照说明安装了相关的软件

When I configured TGIT, there was an error and the function was unavailable. I had installed the relevant software according to the instructions。
![image](https://user-images.githubusercontent.com/5148826/32932314-d1aa2a02-cba2-11e7-9a10-8c0090c91352.png)

**Comment by sboulema** [comment]
I am unable to reproduce this. I get the option dialog after installing TGit. 

Maybe try reinstalling the extension? Maybe try a fresh/new visual studio profile?
