### ISSUE TITLE
command "names" in keyboard customization are not unique

### ISSUE THREAD

**Issue by MartinL0815** [sboulema/TGit#38]
Sincerely, the names of the commands listed in the keyboard customization starting with `TGIT.` are not unique.
If I want to assign a shortcut to "TGit.ShowLog", than I don't know if I assign for the "global" or the document related "Show Log" command.
Same for all commands, that exist doubled "global" and document related.

Any chance for an enhancement to ease the assignment of keyboard shortcuts?

Would an update enhancing command names remove existing keyboard shortcuts?

**Comment by sboulema** [comment]
Thanks for the very good suggestion, these small enhancements also count!

The newly released version has unique command names. 
Any previously set keyboard shortcuts will be preserved.
