### ISSUE TITLE
TGitPackage package for VS2013 has a dependency on VS2015 shell assembly

### ISSUE THREAD

**Issue by KocourKuba** [sboulema/TGit#39]
No 2015 VS installed on this computer. Only VS2013

  <entry>
    <record>56</record>
    <time>2018/02/14 09:55:03.665</time>
    <type>Information</type>
    <source>VisualStudio</source>
    <description>Begin package load [TGitPackage]</description>
    <guid>{6C58D6E5-11BA-43BA-9A63-A624F264EC06}</guid>
  </entry>
  <entry>
    <record>57</record>
    <time>2018/02/14 09:55:03.681</time>
    <type>Error</type>
    <source>VisualStudio</source>
    <description>CreateInstance failed for package [TGitPackage]</description>
    <guid>{6C58D6E5-11BA-43BA-9A63-A624F264EC06}</guid>
    <hr>80070002</hr>
    <errorinfo>Could not load file or assembly 'Microsoft.VisualStudio.Shell.14.0, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.</errorinfo>
  </entry>
  <entry>
    <record>58</record>
    <time>2018/02/14 09:55:03.681</time>
    <type>Error</type>
    <source>VisualStudio</source>
    <description>End package load [TGitPackage]</description>
    <guid>{6C58D6E5-11BA-43BA-9A63-A624F264EC06}</guid>
    <hr>80004005 - E_FAIL</hr>
    <errorinfo>Could not load file or assembly 'Microsoft.VisualStudio.Shell.14.0, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.</errorinfo>
  </entry>

**Comment by sboulema** [comment]
Please try the new release!

**Comment by KocourKuba** [comment]
Thanks! Installed and run without problem.
