### ISSUE TITLE
Visual studio runs very slowly with latest versions of TGit

### ISSUE THREAD

**Issue by rlister302** [sboulema/TGit#42]
I noticed a slowdown in Visual Studio when I have TGit version 4.8.28 or later. When I revert back to 4.8.27 everything seems to go back to normal. I'm running Visual Studio 2017 15.7.3.

**Comment by danfecteau** [comment]
I have the exact same problem (TGit 4.8.31 and VS2017 15.7.4).

**Comment by sboulema** [comment]
Shame to hear the drop in performance :(
Also noticed it myself...

Please try this new release and let me know if it is back to old performance levels again: https://github.com/sboulema/TGit/releases/tag/v4.8.32

**Comment by rlister302** [comment]
Will do! Thanks for getting to it so quickly!

**Comment by danfecteau** [comment]
I tried it during ±10 minutes and it works fine on my side. Thank you for the quick fix!

**Comment by rlister302** [comment]
Looks like that resolved the problem. Thanks a bunch!
