### ISSUE TITLE
VS 2013 performance degrade since 4.8.28

### ISSUE THREAD

**Issue by KocourKuba** [sboulema/TGit#43]
Unfortunately, 4.8.32 still have a problem. Disabling TGIT or install 4.8.27 eliminate freezes.

**Comment by sboulema** [comment]
Will take another look! VS 2013 uses a different initialization than VS 2015 and VS 2017, that might cause the slowdown still appearing in VS2013...

**Comment by sboulema** [comment]
Can you please try this one: https://github.com/sboulema/TGit/releases/tag/v4.8.35

**Comment by KocourKuba** [comment]
Yes. Issue fixed. Thanks!
