### ISSUE TITLE
Feature request. git svn support

### ISSUE THREAD

**Issue by KocourKuba** [sboulema/TGit#45]
Could you please add "git svn" commands support? DCommit, Rebase and Fetch?

**Comment by sboulema** [comment]
Will look into adding git svn support!

TortoiseGit Commands:
DCommit: /command:svndcommit /path:""
Rebase: /command:svnrebase /path:""
Fetch: /command:svnfetch /path:""

Gitconfig:
svn-remote.svn.url=
svn-remote.svn.fetch=
svn-remote.svn.branches=
svn-remote.svn.tags=

**Comment by sboulema** [comment]
Please try this new release: https://github.com/sboulema/TGit/releases/tag/v4.9.36

**Comment by KocourKuba** [comment]
Thanks for fast response. I'm trying this build next week ;) I use mixed git svn environment at work ;)

**Comment by KocourKuba** [comment]
Works fine. Thanks!
