### ISSUE TITLE
All hotkeys unreachable

### ISSUE THREAD

**Issue by ygoe** [sboulema/TGit#46]
TGit has keyboard shortcuts for many of its menu commands. All of them look like Ctrl+G, Ctrl+_. Unfortunately, Ctrl+G is already used for "Go to line", and has always been since I can remember. So another prefix for these commands is needed. Sure I can customise them all, but that's a lot of work and the defaults should at least work with the Visual Studio defaults.

**Comment by sboulema** [comment]
Very good point. I like the shortcuts to be that way, but for a default it is a bit invasive.

Get the new release!
https://github.com/sboulema/TGit/releases/tag/v4.9.40
