### ISSUE TITLE
The extension manifest is invalid

### ISSUE THREAD

**Issue by prasunbanik** [sboulema/TGit#47]
Hi,
I am trying to install the extension for Visual Studio 2017 Professional Edition. But it says that "The extension manifest is invalid". Is there any way I can install this extension for VS 2017 Professional Edition. It worked fine with VS 2015 Professional Edition.

Thanks Prasun

**Comment by sboulema** [comment]
Hey, that is weird... The extension does support VS2017 Pro. I have VS2015 Pro and VS2017 Enterprise installed on my current machine and installation works. Will try to see if I can reproduce it on VS2017 Pro.

**Comment by GreenKn1ght** [comment]
I tried to reproduce this issue with VS2017 Pro 15.8.4 and TGit 4.9.40. Uninstallation and installation completed successfully.

**Comment by sboulema** [comment]
Thanks for testing @GreenKn1ght !

@prasunbanik : Maybe try to redownload the vsix file?

**Comment by prasunbanik** [comment]
Hi Samir,

I freshly downloaded the vsix installer file and tried to install the same.
While doing so, I got this error
[image: image.png]

I also tried to install it from the VS Extension menu, then also I get an
error but this error is different. I have also attached the log file that
is generated during the installation for your reference.
[image: image.png]

-- 
Thanks and Regards
Prasun Banik

**Comment by sboulema** [comment]
@prasunbarik images and log did not make it to the GitHub issue page. Can you please attach them?

**Comment by prasunbanik** [comment]
Hi Samir,
Sorry for the late reply. Please find the images attached in the same order.

![image](https://user-images.githubusercontent.com/42652143/46025449-8deec480-c106-11e8-9b5a-8898d92b1de0.png)


![image](https://user-images.githubusercontent.com/42652143/46025430-84655c80-c106-11e8-877c-2473f4c6c80c.png)

**Comment by sboulema** [comment]
Hey,

Especially the last screenshot indicates that it may be caused by a corrupted visual studio installation :(
Maybe try the steps in this thread: 

https://social.msdn.microsoft.com/Forums/vstudio/en-US/6e88f10a-2890-405b-a3a0-cbc7a1031a8f/visual-studio-2017-extensions-and-update-quotcannot-find-setup-engine-instancequot?forum=visualstudiogeneral
