### ISSUE TITLE
revision graph

### ISSUE THREAD

**Issue by shellduddu** [sboulema/TGit#51]
i need the revision graph command, i want to copy this project, but build error, 
please help the children,thanks,thank ,thanks

**Comment by sboulema** [comment]
`:revisiongraph`

> Shows the revision graph for the repository given in /path.To create an image file of the revision graph for a specific path, but without showing the graph window, pass /output:path  with the path to the output file. The output file must have an  extension that the revision graph can actually export to. These are: .svg, .wmf, .gv, .png, .jpg, .bmp and .gif.

https://tortoisegit.org/docs/tortoisegit/tgit-automation.html

**Comment by sboulema** [comment]
Grab the new release!
