### ISSUE TITLE
Serious performance degrade

### ISSUE THREAD

**Issue by KocourKuba** [sboulema/TGit#52]
Last 2 versions cause serious performance degrade.
Every typing or selection in the text editor or even select control in the resource editor leads to call git.exe via cmd.

https://www.dropbox.com/s/3wpw2ub6ck3o16g/bandicam%202018-12-18%2018-20-37-580.mp4?dl=0

**Comment by sboulema** [comment]
Caused by the changes done in #49 :(
Time to kill that feature branch and look for a new solution.
The latest public releases should not be affected by this performance problem
