### ISSUE TITLE
GitFlow: Error during work with local branches only 

### ISSUE THREAD

**Issue by YanumVlad** [sboulema/TGit#53]
I play with addin with local branches only.
GitFlow's Start New Feature fails with:
> git checkout develop 
Already on 'develop'
> git pull 
There is no tracking information for the current branch.
Please specify which branch you want to merge with.
See git-pull(1) for details.
    git pull <remote> <branch>
If you wish to set tracking information for this branch you can do so with:
    git branch --set-upstream-to=<remote>/<branch> develop

Error (405 ms @ 2/12/2019 1:35:18 AM)

I have no remote branches, in addition - I did not find way on how to prevent Pull issuing.

Thanks,
Vlad

**Comment by sboulema** [comment]
Grab the new release!

Go to Tools -> Options -> TGit -> [] Pull changes

**Comment by YanumVlad** [comment]
Glad to hear :))
Unfortunately, I tried to update extension via Visual Studio. Update even did not start: just 1-second show of download dialog and the subsequent closure...
Could you please take a look? :)

**Comment by sboulema** [comment]
Try updating using the vsix file: https://github.com/sboulema/TGit/releases/download/v4.11.58/TGit_4.11.58.vsix

Download and open should start installation.

**Comment by YanumVlad** [comment]
Great!!! Now it works. Thank you very much for so quick response!!

Just as a minor comment, I just noticed the next spelling issue in final line (Succes with sinlge S at the end):
> git checkout develop 
Already on 'develop'
> git checkout -b feature/Feature4 develop 
Switched to a new branch 'feature/Feature4'

Succes (365 ms @ 2/12/2019 1:55:43 PM)

It would be nice to fix as well, if you have time :)

**Comment by sboulema** [comment]
Great to hear!

Wow that spelling issue has gone unnoticed since 2015...

Grab the new release! :rocket:

**Comment by YanumVlad** [comment]
Excellent! Good job! Thanks!
