### ISSUE TITLE
GitFlow: annotated tags for master branch (tag comments needed)

### ISSUE THREAD

**Issue by YanumVlad** [sboulema/TGit#54]
Could you please support annotated tags in GitFlow's End Finish Release item?
For now, only tag itself is created with name of Release.
It would be nice to add comment to tag as well.
Possible usage - short description of release, deployment date, etc.

Thanks,
Vlad

**Comment by sboulema** [comment]
Grab the new release 🚀 

Tools -> Options -> TGit -> [] Use annotated tags

**Comment by YanumVlad** [comment]
Thanks!!! It works now perfectly!
Now I can use your tool for full prod deployment without additional tools / manual steps. :) 

The only very minor issue: there is a spelling error in Tools -> Options -> TGit -> [] - 
 Use annotated tags:
When finishing a release use a[n] annotated tag.

**Comment by sboulema** [comment]
Great to hear!

Will fix the spelling mistake... next time I'll just make my extensions in Dutch ;)

**Comment by YanumVlad** [comment]
Samir, I just checked Finish Hotfix menu item as final testing (frogot about it in the beginning).
It does not raise tag message dialog.
Could you please add it as well? :)

These changes as connected and consistent: thus I did not created extra  issue...

**Comment by sboulema** [comment]
You know the drill by now...

Grab the new release 🚀 ;)

**Comment by YanumVlad** [comment]
Thank you very much!!!! :)
