### ISSUE TITLE
Ability to reinit GitFlow on demand

### ISSUE THREAD

**Issue by YanumVlad** [sboulema/TGit#55]
Hello,

Could you please tell how can I reinit GitFlow?
On first run I was able to use Init dialog to setup branches and prefixes?
For now, structure and prefixes are subject to change. However, I cannot reinit extension.
Remove / reinstall does not help.

Thanks,
Vlad

**Comment by elmanav** [comment]
In the .git folder the file "config" (text content) contains all the information from the Init GitFlow dialog (gitflow prefix). It can be changed.

**Comment by sboulema** [comment]
Busy adding a new menu options to trigger the UI again for easy editing!

**Comment by sboulema** [comment]
Grab the new release! 🚀
