### ISSUE TITLE
Switch to master on GitFlow Finish Hotfix / Finish Release

### ISSUE THREAD

**Issue by YanumVlad** [sboulema/TGit#56]
Hi,

I really like your extension. My team is using it heavily.
The next issue makes some trouble:
When we complete hotfix / release, we need to switch to master for final deployment.
It is a must: we need to ensure that master merge is 100% OK, and perform deployment from it.
Current behavior - switch to develop branch (what extension is doing) and then switch to master. (2 switch are in action).
My db solution is very heavy. Thus, switch to/from takes really huge time.

Thus, additional setting to select switchTO branch may help us.

Thanks,
Vlad

**Comment by sboulema** [comment]
Hey,

> When the release is finished, the release branch is merged into master and into develop too, to make sure that any changes made in the release branch aren’t accidentally lost by new development. - https://datasift.github.io/gitflow/IntroducingGitFlow.html

Would your problem be solved by using the GitHubFlow menu in TGit?
