### ISSUE TITLE
Where stash pop?

### ISSUE THREAD

**Issue by jwidar** [sboulema/TGit#57]
I might be ignorant, but where is the stash pop equivalent in TGit?
I use _Create stash_ and there is _Apply stash_ but that's not the same thing as _Stash pop_, which is available both in regular git and TortoiseGit.

**Comment by sboulema** [comment]
It is not you! That one is not yet implemented.

Will add it in a next release!

`:stashpop`

**Comment by sboulema** [comment]
Ok that was easy.

Grab the new release! 🚀

**Comment by jwidar** [comment]
Wow, that was fast.
Thanks!
