### ISSUE TITLE
How to change TGit menu place in VS2019

### ISSUE THREAD

**Issue by MartinL0815** [sboulema/TGit#60]
Since using VS2019 the TGit menu is located in the Extensions main menu item.
How to get the TGit menu back as own main menu item?

**Comment by sboulema** [comment]
Not possible unfortunately 😞. Menu location is now determined by VS.

**Comment by mkamoski** [comment]
@MartinL0815 @sboulema -- It seems to me that there is a kind of workaround to the "how to get Tgit onto the main menu" question. In Visual Studio 2019, if one chooses > View, > Toolbars, > Tgit = checked... then one can click on the toolbar and choose "add or remove buttons", and even "customize", and then one can essentially get to "one click menu items on the main menu" which (it seems) may (kind of) solve the "how to get the Tgit menu back as its own main menu item" issue. It is not exactly what you are asking for Martin, but it may be close enough for a workaround. Maybe. Etc. HTH. Thanks. -- Mark Kamoski
