### ISSUE TITLE
Icons are not visible when running as Administrator

### ISSUE THREAD

**Issue by mefmund** [sboulema/TGit#62]
When i'm using "normal" user everything works fine and icons are visible, but when i switch to administrator.
I'm using Visual Studio Professional 2019
![image](https://user-images.githubusercontent.com/23142365/71970999-fe412c80-3209-11ea-9d8f-c3514971bac0.png)

**Comment by sboulema** [comment]
Sounds a lot like this issue: https://github.com/sboulema/TGit/issues/49

Unfortunately still haven't found a solution :(
