### ISSUE TITLE
Maybe show the Tgit version number in Settings and/or in an About menu?

### ISSUE THREAD

**Issue by mkamoski** [sboulema/TGit#64]

**Comment by sboulema** [comment]
You can see the TGit version number here:

- Extensions -> Manage Extensions -> Installed -> TGit

Saves me a lot of work, instead of creating an about window

**Comment by mkamoski** [comment]
Samir, that is perfect, and sorry as I forgot about that location for the version. Great job. Thanks. Mark Kamoski.

**Comment by mkamoski** [comment]
All set. Thanks.
