### ISSUE TITLE
TGit does not appear on VS2017 menu

### ISSUE THREAD

**Issue by MuratOzsoyler** [sboulema/TGit#69]
I tried the actions mentioned in #63 but no avail.

CPU              Intel(R) Core(TM) i7-6650U CPU @ 2.20GHz   2.21 GHz
RAM	     16,0 GB
Architecture  64 bit işletim sistemi, x64 tabanlı işlemci
Edition           Windows 10 Pro
Version	      21H1

**Comment by sboulema** [comment]
Grab the new release! 🚀

**Comment by MuratOzsoyler** [comment]
Thank you very much with your quick action. Menu appears as it should be now.

By the way I thank you for this awesome extension. It very much ease our work flow.
